steps:
# - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       chmod +x ./script.sh
#       ./script.sh

# - name: 'ubuntu'
#   args: ['bash', './subs.sh']
#   secretEnv: ['USERNAME', 'PASSWORD']

# - name: gcr.io/$PROJECT_ID/envsubst
#   args: ["env.json"]
#   env:
#   - 'BUILD_ID=$BUILD_ID'
#   - 'PROJECT_ID=$PROJECT_ID'
#   secretEnv: ['USERNAME', 'PASSWORD']

# - name: 'ubuntu'
#   args: ['bash', './testing.sh']
#   secretEnv: ['USERNAME', 'PASSWORD']
  
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Authenticate to Google Cloud
      gcloud auth configure-docker us-docker.pkg.dev
      
      # Set multiple variables
      token=$(gcloud auth print-access-token) 
      # project=$(gcloud config get-value project | head -n 1)
      region="us-central1"
      
      # Write variables to a file
      echo "token=${token}" >> /workspace/env_vars.txt
      # echo "project=${project}" >> /workspace/env_vars.txt
      echo "region=${region}" >> /workspace/env_vars.txt

- name: 'us-docker.pkg.dev/appintegration-toolkit/images/integrationcli:latest'
  entrypoint: 'sh'
  args:
    - '-c'
    - |

      ls

      cat env.json
      cat env-test.json

      # echo "project id -> $PROJECT_ID"
      # echo "location -> $LOCATION"

      # Load the variables
      source /workspace/env_vars.txt
      
      # Run the integrationcli command
      integrationcli prefs set -p "$PROJECT_ID" -r "$region" -t "$token" 
      integrationcli integrations list
      integrationcli integrations apply -f ./applicationIntegration -e dev --wait=true

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/$_PASSWORD_SECRET_NAME/versions/latest
    env: 'PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/$_USERNAME_SECRET_NAME/versions/latest
    env: 'USERNAME'