steps:
# - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       chmod +x ./script.sh
#       ./script.sh

# - name: 'ubuntu'
#   args: ['bash', './subs.sh']
#   secretEnv: ['USERNAME', 'PASSWORD']

# - name: gcr.io/$PROJECT_ID/envsubst
#   args: ["env.json"]
#   env:
#   - 'BUILD_ID=$BUILD_ID'
#   - 'PROJECT_ID=$PROJECT_ID'
#   secretEnv: ['USERNAME', 'PASSWORD']

# - name: 'ubuntu'
#   args: ['bash', './testing.sh']
#   secretEnv: ['USERNAME', 'PASSWORD']
  
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Authenticate to Google Cloud
      gcloud auth configure-docker us-docker.pkg.dev
      
      # Set multiple variables
      token=$(gcloud auth print-access-token) 
      # project=$(gcloud config get-value project | head -n 1)
      region="us-central1"
      
      # Write variables to a file
      echo "token=${token}" >> /workspace/env_vars.txt
      # echo "project=${project}" >> /workspace/env_vars.txt
      echo "region=${region}" >> /workspace/env_vars.txt

- name: 'us-docker.pkg.dev/appintegration-toolkit/images/integrationcli:latest'
  entrypoint: 'sh'
  args:
    - '-c'
    - |

      ls

      # cat env.json
      # cat env-test.json

      # echo "project id -> $PROJECT_ID"
      # echo "location -> $LOCATION"
      # Load the variables
      source /workspace/env_vars.txt
      
      # Run the integrationcli command
      integrationcli prefs set -p "$PROJECT_ID" -r "$region" -t "$token" 
      integrationcli integrations list

      # integrationcli integrations apply -f ./applicationIntegration -e dev --wait=true

      integrationcli integrations apply -f ./applicationIntegration/testing1 -e dev --verbose --wait=true
      integrationcli integrations apply -f ./applicationIntegration/testing2 -e dev --verbose --wait=true


# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     # Fetch the service account key from Secret Manager
#     # gcloud secrets versions access latest --secret=cloud-build-sa-key > /tmp/key.json

#     # Authenticate using the service account key
#     # gcloud auth activate-service-account --key-file=/tmp/key.json

#     # gcloud auth login

#     # Deploy the Cloud Function
#     gcloud functions deploy helloWorld123 \
#       --runtime nodejs20 \
#       --trigger-http \
#       --allow-unauthenticated \
#       --region=us-central1 \
#       --source=cloudFunction \
#       --gen2 \
#       --entry-point=hey

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
# availableSecrets:
#   secretManager:
#   - versionName: projects/$PROJECT_ID/secrets/$_PASSWORD_SECRET_NAME/versions/latest
#     env: 'PASSWORD'
#   - versionName: projects/$PROJECT_ID/secrets/$_USERNAME_SECRET_NAME/versions/latest
#     env: 'USERNAME'