name: Deploy Cloud Function

on: 
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes
        id: check_changes
        run: |
          git fetch origin main
          git diff --quiet origin/main HEAD ./cloudFunction || echo "CHANGES=true" >> $GITHUB_ENV

      - name: 'GCP Auth'
        if: env.changes_detected == 'true'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy if changes detected
        if: env.CHANGES == 'true'
        uses: google-github-actions/deploy-cloud-functions@v3
        with:
          name: 'my-function'
          runtime: 'nodejs22'
          source_dir: './cloudFunction'
          entry_point: 'hey'