on: 
  push:
    branches:
      - 'releases/**'

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'

      - name: 'GCP Auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Install integrationcli'
        run: 'curl -L https://raw.githubusercontent.com/GoogleCloudPlatform/application-integration-management-toolkit/main/downloadLatest.sh | sh -'

      - name: 'Test integrationcli'
        run: |
          token=$(gcloud auth print-access-token)
          project=$(gcloud config get-value project | head -n 1)
          region=us-central1
          $HOME/.integrationcli/bin/integrationcli prefs set -p $project -r $region -t $token

          $HOME/.integrationcli/bin/integrationcli integrations list
          $HOME/.integrationcli/bin/integrationcli connectors list 
          $HOME/.integrationcli/bin/integrationcli authconfigs list 

      - name: 'Create integration JSON '
        run: |
          $HOME/.integrationcli/bin/integrationcli integrations apply -f ./applicationIntegration -e dev --wait=true 

      - name: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v3'
        timeout-minutes: 10
        with:
          name: 'my-function'
          runtime: 'nodejs22'
          source_dir: ./cloudFunction
          entry_point: hey
