name: CICD (Dev, Staging, Prod)

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
  
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  prod-approval-gate:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: approved
        env: 
          ENV_NAME: prod
        run: write-host "Approve for $($env.ENV_NAME)"
    
  prod-deploy:
    needs: prod-approval-gate
    uses: ./.github/workflows/deploy-ui.yml
    with:
      environment: prod
    secrets: inherit