name: Failing Workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fail-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Intentionally fail the job
      run: exit 1