name: Release Workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build
      run: echo "Building the project..."

    - name: Request Approval
      uses: hmarr/approve-pull-request-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
      with:
        message: 'Please approve the release.'

  approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Await approval
      uses: reviewdog/action-approval@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        approvers: 'octocat, hubot'
        comment: 'Please approve this release.'
        reaction: 'eyes'

  deploy:
    runs-on: ubuntu-latest
    needs: approval
    steps:
    - name: Deploy
      run: echo "Deploying the release..."